#!/usr/bin/env bash

mkdir logs
chmod a+rwx logs
docker run \
	-d \
  -p 9000:9000 \
  -p 8778:8778 \
  --rm \
  --env "PLAY_APPLICATION_SECRET=very-long-secret-for-entropy" \
  --mount type=bind,source="$(pwd)/logs",target=/opt/docker/logs \
  play-scala-with-jmx:latest
